var config = {
    'server' : 'http://54.255.164.213:8000',
    'sitserver' : 'https://sitemployees.blackbuck.com',
    'autoUpdateTime': 30,
    'apiGatewayUrl': 'https://api-systemtest.blackbuck.com',
    'payments_url': 'https://api-systemtest.blackbuck.com/payment-service',
    's3url': '//zinka-devl.s3.amazonaws.com/',
    'GoogleAPIKey': 'AIzaSyBIs836ff9DGX_7BSr41UCKGvPok__0N7k',
    'StompUrl': 'https://systemtest.blackbuck.com/stomp',
    'callsAudioS3url': 'https://zinka-backups.s3.amazonaws.com/callrecords/',
    'GoogleClientId': 'gme-blackbuck',
    'enableLog': false,
	// 'freshDeskURL' : 'https://inps.freshdesk.com/api/v2',
	'freshDeskURL' : 'http://54.255.164.213:3002/api/v2',
	'freshDeskAuth': '4mR1doOIaynn0CxKFUC',
	'hackBBWeb' : 'http://54.255.164.213:8000/api',
	// 'hackBBWebIPS' : 'http://54.255.164.213:8081/inbound-support',
	'hackBBWebIPS' : 'http://13.250.9.186:8081/inbound-support',
    'signInClientId': '747398026184-flk3k8nav6ffv7r3akut6upbqfldj450.apps.googleusercontent.com',
    'logoutRedirectUrl': 'https://sitemployees.blackbuck.com',
    'growthHacksUrl': 'https://sit-growthhacks.blackbuck.com',
};
